name: GPT-Sandbox

on:
  push:
    branches: [ master ]

jobs:
  archive-build-artifacts:
    runs-on: [self-hosted, Linux, dev-1] 
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3


      - name: Step 1 - Download all required software (Python)
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 python3-pip -y

    
      - name: Step 2 - Download all required software (Node 16)
        uses: actions/setup-node@v2
        with:
            node-version: '16'
          

      - name: Step 3 - Download all required software (yarn)
        run: |
          sudo apt install npm
          sudo npm install --global yarn


      - name: Step 4 - Create a virtual environment in root directory
        run: |
          cd /
          sudo apt install python3.8-venv
          sudo python3 -m venv gpt_lab
          source gpt_lab/bin/activate
            

      - name: Step 5 - Install requirements
        run: |
          pip install -r api/requirements.txt
          pip install werkzeug==2.0.3


      - name: Step 6 - Create file and add secret key from OpenAI Website
        run: |
          sudo echo "OPENAI_KEY= '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'" > ~/openai.cfg


      - name: Step 7 - Set environment variable to read the secret key
        run: export OPENAI_CONFIG=/home/devops1/openai.cfg

      - name: Step 8 - Run yarn install in the root directory
        run: |
          cd /
          sudo yarn install
    
      - name: Step 9 - Test to see if environment is set up properly
        run: python3 examples/run_latex_app.py

    
      - name: Step 10 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: /gpt_lab 
